[theme]
primaryColor="#4F46E5"         # Indigo 600
backgroundColor="#0B1220"      # Navy/Slate
secondaryBackgroundColor="#111827" # Gray-900
textColor="#E5E7EB"            # Gray-200
font="sans serif"
