[theme]
primaryColor="#4F46E5"
backgroundColor="#0B1220"
secondaryBackgroundColor="#111827"
textColor="#E5E7EB"
font="sans serif"

[server]
# Prevent "inotify instance limit reached" restarts on Streamlit Cloud
fileWatcherType = "none"
